questions/urls.py
from django.urls import path
from . import views
app_name = 'questions'
urlpatterns=[
    path('',views.index,name='index'),
    path('<questiontext>/', views.process_response, name='process_response'),
    path('send_email/<ismail>/<issms>', views.send_email, name='send_email'),
]

trenching/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('signin/', views.sign_in,name='signin'),
    path('',views.home,name='homepage'),
    path('admin/', admin.site.urls),
    path('questions/',include('questions.urls', namespace='questions')),
    path('signup/',views.sign_up,name='signup'),
    path('logout/', views.logout_view, name='logout'),
    
]

questions/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
class Text_Question(models.Model):
    question_text = models.CharField(max_length=255)
    date_created=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.question_text

class Response(models.Model):
    question=models.ForeignKey(Text_Question,on_delete=models.CASCADE)
    next_yes = models.ForeignKey(Text_Question, related_name='next_yes', on_delete=models.SET_NULL, null=True,blank=True)
    next_no = models.ForeignKey(Text_Question, related_name='next_no', on_delete=models.SET_NULL, null=True,blank=True)
    next = models.ForeignKey(Text_Question, related_name='next', on_delete=models.SET_NULL, null=True,blank=True)
    sms=models.BooleanField(default=False)
    mail=models.BooleanField(default=False)
    date_created=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.question)
    


class Supervisor(models.Model):
    user=models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    name=models.CharField(max_length=50, blank=True, null=True)
    mail_address=models.EmailField(max_length=50, blank=True, null=True)
    phone_number=models.CharField(max_length=14, blank=True, null=True)
    def __str__(self):
        return str(self.user)

trenching/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django import forms

class EmailForm(forms.Form):
    submit = forms.CharField(widget=forms.PasswordInput)

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    # birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')
    email = forms.EmailField()
    supervisor_name = forms.CharField(max_length=100, required=False, label="Supervisor's Name")
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2','supervisor_name']

class SignInForm(AuthenticationForm):
    1

questions/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Text_Question,Response,Supervisor
from django.core.mail import send_mail
from twilio.rest import Client


def index(request, questiontext=None):
    if questiontext is None:
        answer = Text_Question.objects.first()
    else:
        answer = Text_Question.objects.filter(question=questiontext)

    # option = Response.objects.filter(question=answer)
    return render(request, 'questions/index.html', {'answer': answer})

def process_response(request,questiontext):
    if request.method == 'POST':
        queryset = Response.objects.filter(question__question_text__contains=questiontext).values_list('id',flat=True)
        answernum=0
        if queryset:  # Check if the queryset is not empty
            answernum = queryset[0]
        answer=Response.objects.get(id=answernum)
        option = request.POST.get('option')
        if option=='next':
            query = Response.objects.filter(question__question_text__contains=answer.next).values_list('id',flat=True)
            answern=0
            if query:
                answern = query[0]
            check=Response.objects.get(id=answern)
            return render(request,'questions/index.html',{'answer': answer,'option':option,'check':check})
        elif option=='no':
            query = Response.objects.filter(question__question_text__contains=answer.next_no).values_list('id',flat=True)
            answern=0
            if query:
                answern = query[0]
            check=Response.objects.get(id=answern)
            return render(request,'questions/index.html',{'answer': answer,'option':option,'check':check})
        elif option=='yes':
            query = Response.objects.filter(question__question_text__contains=answer.next_yes).values_list('id',flat=True)
            answern=0
            if query:
                answern = query[0]
            check=Response.objects.get(id=answern)
            return render(request,'questions/index.html',{'answer': answer,'option':option,'check':check})
        else:
            return render(request,'questions/send_email.html')

def send_email(request,ismail,issms):
    user = request.user
    id=Supervisor.objects.filter(user=user).values_list('id',flat=True)
    if id:  # Check if the queryset is not empty
        answernum = id[0]
    supervisor_info=Supervisor.objects.get(id=answernum)
    mail=supervisor_info.mail_address
    phone=supervisor_info.phone_number
    sendermail='your_email'
    if ismail.lower() == 'true':
        ismail = True
    else:
        ismail = False

    if issms.lower() == 'true':
        issms = True
    else:
        issms = False

    if request.method == 'POST':
        if issms and ismail:
            account_sid = 'your_sid'
            auth_token = 'your_token'
            client = Client(account_sid, auth_token)
            client.messages.create(
            from_='your_number',
            body='This is a test message.',
            to=phone
            )
            send_mail(
            'Test',
            'This is a test message.',
            sendermail,
            [mail],
            fail_silently=False,
            )
            return HttpResponse('Email and SMS sent successfully.')
        elif ismail:
            send_mail(
            'Test',
            'This is a test message.',
            sendermail,
            [mail],
            fail_silently=False,
            )
            return HttpResponse('Email sent successfully.')
        elif issms:
            account_sid = 'your_sid'
            auth_token = 'your_token'
            client = Client(account_sid, auth_token)
            client.messages.create(
            from_='your_number',
            body='This is a test message.',
            to=phone
            )
            return HttpResponse('SMS sent successfully.')
    else:
        return HttpResponse('Email Failled.')
    

trenching/views.py
from .forms import SignUpForm,SignInForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse
def home(request):
    return render(request,'trenching/home.html')
def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            supervisor_name = form.cleaned_data['supervisor_name']
            return render(request, 'trenching/home.html', {'form': form})
        else:
            return HttpResponse("Please Enter Valid Information")
    else:
        form = SignUpForm()
    return render(request, 'trenching/signup.html', {'form': form})



def sign_in(request):
    if request.method == 'POST':
        form = SignInForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('homepage')  # Redirect to home page after successful sign-in
    else:
        form = SignInForm()
    return render(request, 'trenching/signin.html', {'form': form})


from django.shortcuts import redirect
from django.contrib.auth import logout

def logout_view(request):
    logout(request)
    return redirect('homepage')

questions/templates/questions/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>trenching</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello, world!</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

questions/templates/questions/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Questionnaire</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            text-align: center;
        }
        h1 {
            color: #333;
            margin-top: 50px;
        }
        form {
            margin-top: 20px;
        }
        button {
            padding: 7px 14px;
            font-size: 16px;
            cursor: pointer;
            border: none;
            border-radius: 5px;
            margin: 0 10px;
        }
        button[type="submit"] {
            background-color: #007bff;
            color: #fff;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        p {
            margin-top: 20px;
        }
        a {
            color: #007bff;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    {% if request.user.is_authenticated %}
        <div class="container">
            <a href="{% url 'logout' %}" class="button">Log Out</a>
            <a href="{% url 'homepage' %}" class="button">Home</a>
        </div>
        {% if option == 'yes' %}
            {% if check.next_yes or check.next_no %}
                <h1>{{ answer.next_yes }}</h1>
                <form action="{% url 'questions:process_response' answer.next_yes %}" method="post" id="responseForm">
                    {% csrf_token %}
                    <button type="submit" name="option" value="yes">Yes</button>
                    <button type="submit" name="option" value="no">No</button>
                </form>
            {% elif check.next %}
                <h1>{{ answer.next_yes }}</h1>
                <form action="{% url 'questions:process_response' answer.next_yes %}" method="post" id="responseForm">
                    {% csrf_token %}
                    <button type="submit" name="option" value="next">Next</button>
                </form>
            {% else %}
                <h1>{{ answer.next_yes }}</h1>
                {% if check.mail or check.sms %}
                    <form action="{% url 'questions:send_email' check.mail check.sms %}" method="post" id="responseForm">
                        {% csrf_token %}
                        <p>Please <button type="submit">submit</button> the results.</p>
                    </form>
                {% else %}
                    <p>Thank you. <a href="{% url 'homepage' %}">Back to home</a>.</p>
                {% endif %}
            {% endif %}
        {% elif option == 'no' %}
            {% if check.next_yes or check.next_no %}
                <h1>{{ answer.next_no }}</h1>
                <form action="{% url 'questions:process_response' answer.next_no %}" method="post" id="responseForm">
                    {% csrf_token %}
                    <button type="submit" name="option" value="yes">Yes</button>
                    <button type="submit" name="option" value="no">No</button>
                </form>
            {% elif check.next %}
                <h1>{{ answer.next_no }}</h1>
                <form action="{% url 'questions:process_response' answer.next_no %}" method="post" id="responseForm">
                    {% csrf_token %}
                    <button type="submit" name="option" value="next">Next</button>
                </form>
            {% else %}
                <h1>{{ answer.next_no }}</h1>
                {% if check.mail or check.sms %}
                    <form action="{% url 'questions:send_email' check.mail check.sms %}" method="post" id="responseForm">
                        {% csrf_token %}
                        <p>Please <button type="submit">submit</button> the results.</p>
                    </form>
                {% else %}
                    <p>Thank you. <a href="{% url 'homepage' %}">Back to home</a>.</p>
                {% endif %}
            {% endif %}
        {% elif option == 'next' %}
            {% if check.next_yes or check.next_no %}
                <h1>{{ answer.next }}</h1>
                <form action="{% url 'questions:process_response' answer.next %}" method="post" id="responseForm">
                    {% csrf_token %}
                    <button type="submit" name="option" value="yes">Yes</button>
                    <button type="submit" name="option" value="no">No</button>
                </form>
            {% elif check.next %}
                <h1>{{ answer.next }}</h1>
                <form action="{% url 'questions:process_response' answer.next %}" method="post" id="responseForm">
                    {% csrf_token %}
                    <button type="submit" name="option" value="next">Next</button>
                </form>
            {% else %}
                <h1>{{ answer.next }}</h1>
                {% if check.mail or check.sms %}
                    <form action="{% url 'questions:send_email' check.mail check.sms %}" method="post" id="responseForm">
                        {% csrf_token %}
                        <p>Please <button type="submit">submit</button> the results.</p>
                    </form>
                {% else %}
                    <p>Thank you. <a href="{% url 'homepage' %}">Back to home</a>.</p>
                {% endif %}
            {% endif %}
        {% else %}
            <h1>{{ answer.question_text }}</h1>
            <form action="{% url 'questions:process_response' answer.question_text %}" method="post" id="responseForm">
                {% csrf_token %}
                <button type="submit" name="option" value="yes">Yes</button>
                <button type="submit" name="option" value="no">No</button>
            </form>
        {% endif %}
    {% else %}
    <p>Please <a href="{% url 'signin' %}">sign in</a> to continue.</p>
    {% endif %}
</body>
</html>

questions/templates/questions/send_email.html
<!-- send_email.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Send Email</title>
</head>
<body>
    <h1>Thanks</h1>
</body>
</html>

questions/templates/trenching/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            text-align: center;
        }
        h1 {
            color: #333;
            margin-top: 50px;
        }
        ul {
            list-style-type: none;
            padding: 0;
            margin-top: 30px;
        }
        li {
            ont-size: 20px;
            margin-bottom: 10px;
        }
        a {
            text-decoration: none;
            color: #007bff;
            font-size: 20px;
            font-weight: normal;
            transition: color 0.3s ease;

        }

        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>
    {% if request.user.is_authenticated %}
        <div class="container">
            <h1> Dear {{ request.user.username }}, Welcome to Our Trenching Application.</h1>
            <div>
                <a href="{% url 'questions:index' %}">Start</a>
            </div>
            <div>
                <a href="{% url 'logout' %}" class="button">Log Out</a>
            </div>
        </div>
    {% else %}
        <h1> Please <a href="{% url 'signin' %}">Sign-in</a> / <a href="{% url 'signup' %}">Sign-up</a> to Use Our Trenching Application.</h1>
    {% endif %}

</body>
</html>

questions/templates/trenching/signin.html
<!DOCTYPE html>
<html>
<head>
    <title>Sign In</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
        }
        h2 {
            text-align: center;
            margin-top: 0;
            color: #333;
        }
        input[type="text"],
        input[type="password"] {
            width: calc(100% - 20px);
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }
        button[type="submit"] {
            width: calc(100% - 20px);
            padding: 10px;
            margin: 10px 0;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    {% if request.user.is_authenticated %}
        <div class="container">
            <h1> Dear {{ request.user.username }},You are already signed in!</h1>
            <a href="{% url 'logout' %}" class="button">Log Out</a>
            <a href="{% url 'homepage' %}" class="button">Home</a>
        </div>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Sign In</button>
        </form>
    {% endif %}
</body>
</html>

questions/templates/trenching/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 30px;
            width: 300px;
            text-align: center;
        }
        h2 {
            margin-top: 0;
            color: #333;
        }
        form {
            margin-top: 20px;
        }
        input[type="text"],
        input[type="password"] {
            width: calc(100% - 20px);
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }
        button[type="submit"] {
            width: calc(100% - 20px);
            padding: 10px;
            margin: 10px 0;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Sign Up</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Sign Up</button>
        </form>
    </div>
</body>
</html>